"""Centralized named constants to avoid magic numbers."""

WINDOW_WIDTH = 420
WINDOW_HEIGHT = 361

GRID_ROWS = 6
GRID_COLUMNS = 7
CONNECT_TILES = 4

TIE_CODE = 2

ILLEGAL_MOVE_SCORE = 1000

CIRCLE_RADIUS = 25

OVERLAY_ALPHA = 96
BUTTON_WIDTH = 180
BUTTON_HEIGHT = 44
BUTTON_SPACING = 24
TITLE_FONT_SIZE = 40
LABEL_FONT_SIZE = 32
VICTORY_TITLE_Y_OFFSET = -20
VICTORY_BUTTONS_TOP_OFFSET = 40
BUTTON_BORDER_RADIUS = 6
BUTTON_INNER_INFLATE = 4

# Basic RGB tuples
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
